server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/lol_team_db
spring.datasource.username=postgres
spring.datasource.password=134679258Czy
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true